# -*- coding: utf-8 -*-
"""Forcast1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ecfH4pNpebXPAtR5V0hD0cM0O-ILgft6
"""

import requests
import pandas as pd
import json
import datetime

zipcode = ["07112", '0', '07112']
result_list = []
forcast_days_num = 2
#cityname = ["London", "Toronto", "Rome", "Sydney"]
#country = ["United Kingdom", "Canada", "Italy", "Australia"]
#region = ["City of London, Greater London", "Ontario", "Lazio", "New South Wales"]


key = "5f7c9d283060480d857194323212906"

count = 0

def forcast_check(forcast_list):
   print(len(forcast_list)) 

   if forcast_days_num == len(forcast_list):
    print("PASS: Days for Forcast appear to match days returned in JSON DATA")
 
   for i in forcast_list:
    print(i['date'])
    print(i['day'])



def error_check(json_data, i):
  result_list = ["location", "error", "error", "location", "error", "error", "location"]
  error_dict = {1002:"API key is invalid", 1003:"Parameter q", 1005:"API request url", 1006:"No location found", 2006:"API key"}


  if result_list[count] == "error":
    if 'error' in json_data:
        error_code = json_data["error"]["code"]
        error_message = json_data["error"]["message"]
        print("$$$ {}".format(error_dict[error_code]))

        if error_dict[error_code] in error_message:
          print("PASS: API error Code Message appears CORRECT for {}".format(error_code))
        else:
          print("FAIL: API error Message INCORRECT for {}".format(error_code))    
    else:
      print("FAIL: JSON DATA should throw an ERROR") 
  else:
      if 'location' in json_data:
        print("PASS: NO API ERROR")
      else:
        print("FAIL: API ERROR SHOULD NOT BE DISPLAYED")



# Function to check for text terms in json info
def check_name(x, keyname, name): 
  checktext = '"{}":"{}"'.format(keyname, name)
  print("Name Search Term: {}".format(checktext))
  if checktext in x:
    print("{} found in json info".format(checktext))
  else:
    print("{} not found in json info: json appears to be not valid".format(checktext))

for zip in zipcode:
  print(zip)
  timezone = "http://api.weatherapi.com/v1/forecast.json?key={}&q={}&days={}".format(key, zip, forcast_days_num)

  print("ZIPCODE: {}".format(zipcode))
  try:
    x = requests.get(timezone)
    z = x.json()
    z_forcast = z['forecast']
    print(z_forcast)
    print(z_forcast.values())
    print("### {}".format(z_forcast['forecastday'][1]['day'].keys()))
    print(len(z_forcast['forecastday']))
    #date1 = z_forcast['forecastday'][1]['date']
  except VisualError:
    print("ERROR")

  forcast_check(z_forcast['forecastday'])
  #print(z.keys())
  #astro_check(z)
  #print(x.text)
  #print("** LOCALTIME: {}".format(z['location']['localtime']))
  #localtime_list = z['location']['localtime'].split(' ')

  #datetime_check(localtime_list, z['location']['localtime'])

  print("Call Status for {} call: {}".format(zip, x))
  #check_name(x.text, "name", cityname[count])
  #check_name(x.text, "country", country[count])
  #check_name(x.text, "region", region[count])
  print("___")
  count = count + 1